import path from "node:path";
import { defineConfig, mergeConfig } from "vite";
import react from "@vitejs/plugin-react";
import { tanstackRouter } from "@tanstack/router-plugin/vite";

// Web (browser) build of the desktop app — Phase 2 Buzz-Web port.
// Same plugins/routes/aliases as vite.config.ts; no Tauri dev-server bits.
// The platform layer reads `import.meta.env.VITE_PLATFORM` to select the
// browser adapters (desktop/src/platform/).
export default defineConfig(async () => ({
  define: {
    "import.meta.env.VITE_PLATFORM": JSON.stringify("web"),
  },
  plugins: [
    tanstackRouter({
      target: "react",
      routesDirectory: "./src/app/routes",
      generatedRouteTree: "./src/app/routeTree.gen.ts",
      virtualRouteConfig: "./src/app/routes.ts",
      quoteStyle: "double",
      semicolons: true,
      routeTreeFileHeader: [
        "// biome-ignore-all lint: generated by TanStack Router",
      ],
    }),
    react(),
  ],
  resolve: {
    alias: {
      "@": "/src",
      "@features-manifest": path.resolve(__dirname, "../preview-features.json"),
    },
  },
  build: {
    outDir: "dist-web",
    rollupOptions: {
      input: path.resolve(__dirname, "index.web.html"),
    },
  },
}));
